### ISSUE TITLE
[Minecraft Modpack] I/O Exception when creating a world

### ISSUE THREAD

**Issue by Sebas-Re** [TheElectronWill/night-config#124]
Hey!

So, I'm not exactly sure if this is the right place to post this (I'm kinda lost here) but for some reason the second time I launch a modpack and create a world, the game throws that exception, forcing me to close everything related to the game (Java, Minecraft, and Curseforge), wait some minutes, and launch everything it back up.

The steps to reproduce the issue are as follows:
```
1. Launch the modpack
2. Create a new world
3. Exit the world and game as you would normally do
4. Re-launch the modpack
5. Create another world
6. I/O Exception pops up

```
https://paste.corebot.dev/urojududur.sql
I translated the exception message, in case you notice it's a bit different from the usual

_NOTE: The config file that is locked by another process isn't always the same one, it's a different config file every time._

**Comment by TheElectronWill** [comment]
Hello,

It seems that some process keeps the config file open (possibly multiple config files) when you exit the game. When you launch the game again, it can't use the file and crashes.

The problem (bug) is in the "thing" (possibly a mod of the modpack, possibly something else) that keeps the file open. On Windows, you can [use the Resources Monitor to find "who" is using the file](https://superuser.com/questions/117902/find-out-which-process-is-locking-a-file-or-folder-in-windows). You could also try to remove some mods to see if one of them is the problem.

NightConfig is "just" the library that reads and writes the config file. It tries to do its best, but when Windows blocks access to the file there's nothing it can do... It's not the root cause of your problem here :)

**Comment by Sebas-Re** [comment]
Thank you for your response! I'll try what you suggested ^^
