### ISSUE TITLE
Toml parser mapping to record POJO

### ISSUE THREAD

**Issue by sysmat** [TheElectronWill/night-config#127]
- toml:3.6.6
- I'm new to this lib, what is the best way to map from TomlParser CommentedConfig to my record class
- is in this lib something like mapper in com.fasterxml.jackson.dataformat.toml.TomlMapper?

**Comment by sysmat** [comment]
- if I have tokio=`SimpleCommentedConfig:{features=[macros, derive]` how to retrieve array or list?(there is no such method)

**Comment by TheElectronWill** [comment]
Hello!

The best way to (de)serialize objects is to use an `ObjectConverter`. You can find more information [in the wiki](https://github.com/TheElectronWill/night-config/wiki/Object-serialization).

To answer your second question "how to retrieve a list of value", the answer is: exactly like a normal value! NightConfig has a type parameter on the `get` method, so you do:

```java
config.<String>get("myString");
config.<List<String>>get("myList");
```

Since Java (or Scala, or whetever Java-compatible language you use) infers some types, you can also write:

```java
List<String> features = tokio.get("features");
```

**Comment by sysmat** [comment]
Ah, my bad, more natural for me would be `config.get<String>("myString");`, but @TheElectronWill works like a charm
