### ISSUE TITLE
Loading default Resource points to night-config's JAR, not to resources folder

### ISSUE THREAD

**Issue by brainbytes42** [TheElectronWill/night-config#128]
Hi,

thanks for this library!

I wanted to specify a default config file in my resources-folder using `FileConfig.builder(configPath).defaultResource(default)`, but the resource won't be found, as the FileNotFoundAction points to the night-config's JAR:
https://github.com/TheElectronWill/night-config/blob/4ac1b3c8c26815dea5a97a88e8337589a78e6d7c/core/src/main/java/com/electronwill/nightconfig/core/file/FileNotFoundAction.java#L106
`FileNotFoundAction.class.getResource("") = jar:file:/C:/Users/[...]/.gradle/caches/[...]/com.electronwill.night-config/core/3.6.6/[...]/core-3.6.6.jar!/com/electronwill/nightconfig/core/file/`

I'd suggest `return copyData(Thread.currentThread().getContextClassLoader().getResource(resourcePath));` to replace this line. This resolves correctly to the resources directory (`.../build/resources/main/`).

**Comment by mani1232** [comment]
I had the same problem, but I found this way: https://github.com/mani1232/CustomBot/blob/master/src/main/java/ua/mani123/config/configUtils.java#L48

**Comment by TheElectronWill** [comment]
Thanks for reporting!
You can always use `copyData` and call `getResource` on your class or classloader, so that is resolves properly.
I'll test on my end but to clarify: does the problem occur with absolute paths (i.e. `/my/package/resource`) or is just when using relative ones?

**Comment by TheElectronWill** [comment]
A note about the `getContextClassLoader`: I'm reluctant to use it, because it's more like [an artifact of the past](https://stackoverflow.com/questions/1771679/difference-between-threads-context-class-loader-and-normal-classloader) than a proper way to get "the right" classloader. Also, [it may not exist](https://stackoverflow.com/questions/23178915/java-thread-context-classloader-how-does-it-work) in some environments.

The best solution is to pass an *absolute* path to your resource, or to call `YourClass.class.getResource` yourself. See [Class#getResource](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getResource-java.lang.String-).

The docs and wiki should be updated to reflect this.
