### ISSUE TITLE
com.electronwill.nightconfig.core.io.ParsingException: Not enough data available

### ISSUE THREAD

**Issue by drizzs** [TheElectronWill/night-config#66]
https://pastebin.com/JhYmRCs8

Can you explain what i did to make this happen so i can fix it? it worked until i tried to add a biome to my mod now i get this error even after i went back to what i had before i started adding the biome....... so i have no idea what happened it was all working fine before...................

**Comment by TheElectronWill** [comment]
Hello!

This error is likely caused by an invalid configuration file (`.toml` extension). Judging by the stack trace you've posted, it seems that there is, at the end of a file, a dotted key that doesn't terminate properly.

That is, a situation like this:
```toml
key = "value" # this line is ok, the next line is wrong
dotted.key.here
```
See how the last thing in the file is `here`, a part of a TOML key. In TOML a key must be followed by a `=` sign and then a value (like the first line in my example). NightConfig is looking for this `=` to know where the key stops, but can't find it and therefore throws `ParsingException: Not enough data available`.

You should fix this file to make it valid.

**Comment by drizzs** [comment]
Super weird, i actually went back to an older version and changed everything back to the new version then i tried to reproduce the steps and when i did exactly what i did the first time it worked fine. So idk why it happened in the first place but i just reverted to save time. Next time this happens i'll know how to solve it! Thanks this makes perfect sense!

**Comment by TheElectronWill** [comment]
You're welcome! Happy modding :smiley:
