### ISSUE TITLE
Cannot parse files that contain UTF8 BOM

### ISSUE THREAD

**Issue by espidev** [TheElectronWill/night-config#67]
Hey,

So some of the users of my project insist on using Windows notepad to edit their configs, but end up with errors since it seems that nightconfig issues errors when it attempts to load files that are saved with it (Invalid bare key: ?#). It works fine when I use other proper text editors. Is there a fix for this, or am I doing something wrong?

**Comment by TheElectronWill** [comment]
Hello,

It seems like a BOM problem: if the file's encoding is misconfigured, the editor will insert a few extra bytes at the beginning of the file, creating an invalid config key.

Solution: The users should choose the encoding `UTF8 without BOM` or something like that.

**Comment by TheElectronWill** [comment]
On a second thought, NightConfig could detect the BOM and skip it. Adding this to my todo list!

**Comment by espidev** [comment]
Any update on this?

**Comment by TheElectronWill** [comment]
Still on my TODO-list, I'll implement the feature during my next holidays :smiley:

**Comment by juliand665** [comment]
> I'll implement the feature during my next holidays

lies! just tracked a user's bug report down to this lol

**Comment by TheElectronWill** [comment]
whoops! :eyes:
In my defence, a BOM (Byte Order Mark) is useless for UTF-8 because the standard imposes the order, on all platforms. But I haven't forgotten this issue ^^

**Comment by ProfessorFartsalot** [comment]
Same issue using the built in editor on my pterodactyl panel and forge 40.2.0. Pterodactyl has syntax highlighting too, so having this fixed would be really nice. I shouldn't have to download the config file, edit it in notepad++ and then reupload it to load a config imo.

**Comment by TheElectronWill** [comment]
I take note of the high demand of this feature ;)

The "pterodactyl" editor looks good, indeed, but does it actually add a BOM? I have no idea why it would do that, instead of just editing the file as it finds it on the disk :thinking: 
If it's not pterodactly, I shall ask: where does the file comes from?

**Comment by ProfessorFartsalot** [comment]
I'm thinking this may actually already be supported. I have tried editing a toml file just recently with Notepad++ and regardless of UTF-8 or ANSI, it still gets reset. I'll attach a zip containing Storm-5.toml (the reset toml file) and Storm.toml (the one edited by the panel) for analysis.

Pterodactyl is a web panel for server hosts. They have an embedded file editor that loads the files from a Docker filesystem (which is why it's named /home/container). I had no issues editing a config file from extreme reactors, which now makes me wonder if there's an issue with Weather2's config system in particular.

[Weather2.zip](https://github.com/TheElectronWill/night-config/files/10360588/Weather2.zip)

**Comment by ProfessorFartsalot** [comment]
Here is another sample. This one is more of a nuisance to me as every server restart resets it no matter what I do. 
[Misc.zip](https://github.com/TheElectronWill/night-config/files/10360608/Misc.zip)

Misc-1.toml.bak is the one I had saved and thought it would work, as I only edited misc-1.toml in the panel and saved it. However, it regenerated it with defaults (Misc.toml). I really don't understand why one mod can be configured while another does not seem to like it.

**Comment by TheElectronWill** [comment]
Thanks for the files! There is no [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) in them (and this GitHub issue is specifically for the BOM). If it only happens with some mods it might be a bug in it.

Do the logs say something? Is there an error?

**Comment by ProfessorFartsalot** [comment]
The only thing I see is

```

[09:18:06] [Thread-0/WARN] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Configuration file /home/container/config/Weather2/Misc.toml is not correct. Correcting
[09:18:06] [Thread-0/WARN] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Configuration file /home/container/config/Weather2/Sand.toml is not correct. Correcting
```

**Comment by ProfessorFartsalot** [comment]
It is worth noting that I never even edited this "sand.toml" file that is erroring. The server generated it and it's still an error, so maybe it is indeed a bug with that particular mod?

**Comment by TheElectronWill** [comment]
Hmm, so the config is loaded and then "corrected", I guess with some `ConfigSpec` managed by the mod. Looks like a bug somewhere. In any case I think it would be worth it to report that to the mod :)

**Comment by ProfessorFartsalot** [comment]
I shall do so, thank you!

**Comment by TheElectronWill** [comment]
Note that UTF-16 BOM is supported out-of-the box thanks to Java's `StandardCharsets.UTF_16`. You can pass the charset as a parameter of `ConfigParser#parse`, and the charset will handle the BOM for you. Only the UTF-8 BOM causes problems.
