### ISSUE TITLE
unwritable config file should NOT crash.

### ISSUE THREAD

**Issue by jgilmore** [TheElectronWill/night-config#98]
I'm having a problem with a mod using this library reverting config file changes. So I removed the "writeable" permission, and this caused the server to crash on startup.

This error should be ignored, possibly with a message. NOT a good reason to crash the server.

I'm certain there's another way to solve this problem, and will continue searching, but that doesn't make what you did OK.

**Comment by TheElectronWill** [comment]
Hello,
I'm sorry you've found a bug in a mod.

Note that NightConfig is a general-purpose configuration library. If the library is used to write a config file and this file is not writable, it is normal and expected that it throws an exception. It's the application (in this case, the mod) that uses the library that should handle those exceptions, not NightConfig, because the right thing to do depends on the application. This is how programming works (when you use a language with an exception system).

So in the hand, even though my library appears in your server logs, it's not really at fault here. The root cause is that the mod that you want to use is simply not designed to work without writing the file you've removed the permission from.
